version: '3'
services:

  # rabbitMq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq_dev
  #   ports:
  #    - "15672:15672"
  #    - "5672:5672"

  rabbitMq:
    image: rabbitmq
    container_name: rabbitMq_container

  payments:
    image: payments
    container_name: payments
    ports:
     - "8010:8080"

  tokens:
    image: tokens
    container_name: tokens
    ports:
     - "8020:8080"

  accounts:
    image: accounts
    container_name: accounts
    ports:
     - "8030:8080"

  reports:
    image: reports
    container_name: reports
    ports:
     - "8040:8080"